---
title: "Tarea 3"
author: "Daniel Eduardo Macias Estrada"
subtitle: Repasando matrices
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Pregunta 1

Consideremos las matrices:

$$A = \begin{pmatrix}
0 & 1 & -2\\
2 & 3 & -1\\
1 & -1 & 5
\end{pmatrix}\qquad B = \begin{pmatrix}
1 & -1 & 2 & 1\\
2 & -2 & 2 & -2\\
-1 & 2 & 1 & 2
\end{pmatrix}\qquad C = \begin{pmatrix}
2\\
0\\
1\\
-4
\end{pmatrix}$$

Realizar las operaciones siguientes:

* $A\cdot B$

$$AB = \begin{pmatrix}
0 & 1 & -2\\
2 & 3 & -1\\
1 & -1 & 5
\end{pmatrix}\begin{pmatrix}
1 & -1 & 2 & 1\\
2 & -2 & 2 & -2\\
-1 & 2 & 1 & 2
\end{pmatrix}$$

$$=\begin{pmatrix}
0\cdot 1 + 1\cdot 2 + (-2)\cdot (-1) & 0\cdot (-1) + 1\cdot (-2) + (-2)\cdot 2 & 0\cdot 2 + 1\cdot 2 + (-2)\cdot 1 & 0\cdot 1 + 1\cdot (-2) + (-2)\cdot 2\\
2\cdot 1 + 3\cdot 2 + (-1)\cdot (-1) & 2\cdot (-1) + 3\cdot (-2) + (-1)\cdot 2 & 2\cdot 2 + 3\cdot 2 + (-1)\cdot 1 & 2\cdot 1 + 3\cdot (-2) + (-1)\cdot 2\\
1\cdot 1 + (-1)\cdot 2 + 5\cdot (-1) & 1\cdot (-1) + (-1)\cdot (-2) + 5\cdot 2 & 1\cdot 2 + (-1)\cdot 2 + 5\cdot 1 & 1\cdot 1 + (-1)\cdot (-2) + 5\cdot 2
\end{pmatrix}$$

$$=\begin{pmatrix}
0+2+2 & 0-2-4 & 0+2-2 & 0-2-4\\
2+6+1 & -2-6-2 & 4+6-1 & 2-6-2\\
1-2-5 & -1+2+10 & 2-2+5 & 1+2+10
\end{pmatrix} = \begin{pmatrix}
4 & -6 & 0 & -6\\
9 & -10 & 9 & -6\\
-6 & 11 & 5 & 13
\end{pmatrix}$$

* $B\cdot C$

$$BC = \begin{pmatrix}
1 & -1 & 2 & 1\\
2 & -2 & 2 & -2\\
-1 & 2 & 1 & 2
\end{pmatrix}\begin{pmatrix}
2\\
0\\
1\\
-4
\end{pmatrix} = \begin{pmatrix}
1\cdot 2 + (-1)\cdot 0 + 2\cdot 1 + 1\cdot (-4)\\
2\cdot 2 + (-2)\cdot 0 + 2\cdot 1 + (-2)\cdot (-4)\\
(-1)\cdot 2 + 2\cdot 0 + 1\cdot 1 + 2\cdot (-4)\\
\end{pmatrix}$$

$$= \begin{pmatrix}
2+0+2-4\\
4+0+2+8\\
-2+0+1-8
\end{pmatrix} = \begin{pmatrix}
0\\
14\\
-9
\end{pmatrix}$$

* $B^t$

$$B = \begin{pmatrix}
1 & -1 & 2 & 1\\
2 & -2 & 2 & -2\\
-1 & 2 & 1 & 2
\end{pmatrix}\qquad B^t = \begin{pmatrix}
1 & 2 & -1\\
-1 & -2 & 2\\
2 & 2 & 1\\
1 & -2 & 2
\end{pmatrix}$$

* $B^t\cdot A$

$$B^tA = \begin{pmatrix}
1 & 2 & -1\\
-1 & -2 & 2\\
2 & 2 & 1\\
1 & -2 & 2
\end{pmatrix}\begin{pmatrix}
0 & 1 & -2\\
2 & 3 & -1\\
1 & -1 & 5
\end{pmatrix}$$

$$= \begin{pmatrix}
1\cdot 0 + 2\cdot 2 + (-1)\cdot 1 & 1\cdot 1 + 2\cdot 3 + (-1)\cdot (-1) & 1\cdot (-2) + 2\cdot (-1) + (-1)\cdot 5\\
(-1)\cdot 0 + (-2)\cdot 2 + 2\cdot 1 & (-1)\cdot 1 + (-2)\cdot 3 + 2\cdot (-1) & (-1)\cdot (-2) + (-2)\cdot (-1) + 2\cdot 5\\
2\cdot 0 + 2\cdot 2 + 1\cdot 1 & 2\cdot 1 + 2\cdot 3 + 1\cdot (-1) & 2\cdot (-2) + 2\cdot (-1) + 1\cdot 5\\
1\cdot 0 + (-2)\cdot 2 + 2\cdot 1 & 1\cdot 1 + (-2)\cdot 3 + 2\cdot (-1) & 1\cdot (-2) + (-2)\cdot (-1) + 2\cdot 5\\
\end{pmatrix}$$

$$= \begin{pmatrix}
0+4-1 & 1+6+1 & -2-2-5\\
0-4+2 & -1-6-2 & 2+2+10\\
0+4+1 & 2+6-1 & -4-2+5\\
0-4+2 & 1-6-2 & -2+2+10
\end{pmatrix} = \begin{pmatrix}
3 & 8 & -9\\
-2 & -9 & 14\\
5 & 7 & -1\\
-2 & -7 & 10
\end{pmatrix}$$

* $C^t\cdot B^t$

$$C = \begin{pmatrix}
2\\
0\\
1\\
-4
\end{pmatrix}\qquad C^t = \begin{pmatrix}
2 & 0 & 1 & -4
\end{pmatrix}\qquad C^t B^t = \begin{pmatrix}
2 & 0 & 1 & -4
\end{pmatrix} \begin{pmatrix}
1 & 2 & -1\\
-1 & -2 & 2\\
2 & 2 & 1\\
1 & -2 & 2
\end{pmatrix}$$

$$= \begin{pmatrix}
2\cdot 1 + 0\cdot (-1) + 1\cdot 2 + (-4)\cdot 1 & 2\cdot 2 + 0\cdot (-2) + 1\cdot 2 + (-4)\cdot (-2) & 2\cdot (-1) + 0\cdot 2 + 1\cdot 1 + (-4)\cdot 2
\end{pmatrix}$$

$$= \begin{pmatrix}
2+0+2-4 & 4+0+2+8 & -2+0+1-8
\end{pmatrix} = \begin{pmatrix}
0 & 14 & -9
\end{pmatrix}$$

## Pregunta 2

Escribid la matriz de orden $3\times4$ que tiene por entrada $(i, j)$ el elemento:

$$a_{ij}= \frac{(-1)^{i+j}}{i+j}$$
Resultado

$$a_{11}=\frac{(-1)^{1+1}}{1+1}=\frac{(-1)^2}{2}=\frac{1}{2} \qquad a_{12}=\frac{(-1)^{1+2}}{1+2}=\frac{(-1)^3}{3}=\frac{-1}{3} \qquad a_{13}=\frac{(-1)^{1+3}}{1+3}=\frac{(-1)^4}{4}=\frac{1}{4}$$
$$a_{14}=\frac{(-1)^{1+4}}{1+4}=\frac{(-1)^5}{5}=\frac{-1}{5} \qquad a_{21}=\frac{(-1)^{2+1}}{2+1}=\frac{(-1)^3}{3}=\frac{-1}{3} \qquad a_{22}=\frac{(-1)^{2+2}}{2+2}=\frac{(-1)^4}{4}=\frac{1}{4}$$
$$a_{23}=\frac{(-1)^{2+3}}{2+3}=\frac{(-1)^5}{5}=\frac{-1}{5} \qquad a_{24}=\frac{(-1)^{2+4}}{2+4}=\frac{(-1)^6}{6}=\frac{1}{6} \qquad a_{31}=\frac{(-1)^{3+1}}{3+1}=\frac{(-1)^4}{4}=\frac{1}{4}$$
$$a_{32}=\frac{(-1)^{3+2}}{3+2}=\frac{(-1)^5}{5}=\frac{-1}{5} \qquad a_{33}=\frac{(-1)^{3+3}}{3+3}=\frac{(-1)^6}{6}=\frac{1}{6} \qquad a_{34}=\frac{(-1)^{3+4}}{3+4}=\frac{(-1)^7}{7}=\frac{-1}{7}$$
$$A = \begin{pmatrix}
^1/_2 & ^{-1}/_3 & ^1/_4 & ^{-1}/_5\\
^{-1}/_3 & ^1/_4 & ^{-1}/_5 & ^1/_6\\
^1/_4 & ^{-1}/_5 & ^1/_6 & ^{-1}/_7
\end{pmatrix}$$

## Pregunta 3

Escribid la matriz de orden $(n+1)\times (n+1)$ que tiene por entrada $(i, j)$ el elemento

$$a_{ij}=\begin{cases}
            0        & \quad \text{si } i > j\\
            1        & \quad \text{si } i = j\\
            K^{j-i}  & \quad \text{si } i < j
         \end{cases}$$

donde $k$ es un número real cualquiera

P.D. Asumiremos que hubo un error con la tercera condición en donde se pone $K^{j-i} \quad \text{si } i>j$, por loq que lo combiaremos a $i<j$

Resultado

$$A = \begin{pmatrix}
1 & K^1 & \cdots & K^{n - 1} & K^{n}\\
0 & 1 & \cdots & K^{n-2} & K^{n-1}\\
\vdots &\vdots & \ddots & \vdots & \vdots\\
0 & 0 & \cdots & 1 & K^{1}\\
0 & 0 & \cdots & 0 & 1\\
\end{pmatrix}$$
         
## Pregunta 4

Dada la matriz:

$$A = \begin{pmatrix}
0 & 1\\
0 & 0
\end{pmatrix}$$

hallad todas las matrices cuadradas de orden $2$, $X$, tales que $AX = 0$

Resultado

Para poder comprobar que 

$$AX=0 \quad X=A^{-1} 0$$
Tenemos que estar seguros que la matriz cuadrada A es regular, por lo tanto, procedemos a realizar dicha operación

$$A^{-1} = \begin{pmatrix}
0 & 1 & | & 1 & 0\\
0 & 0 & | & 0 & 1\\
\end{pmatrix} = Indefinido$$

Al realizar varias operaciones fundamentales, no fue posible lograr las condiciones necesarias para poder crear la matriz inversa de A.

A pesar de esa, sabemos la existencia de la propiedad multiplicativa del $0$, por ello, podemos decir que 

$$A\cdot 0 = 0 \qquad A\cdot X = 0 \qquad \text{por lo tanto} \qquad X=0$$
Es decir, $X$ es igual a una matriz nula de orden $2$

## Pregunta 5

Considerad las matrices

$$A = \begin{pmatrix}
0 & 1\\
0 & 1
\end{pmatrix} \qquad B = \begin{pmatrix}
-1 & -1\\
0 & 0
\end{pmatrix}$$

Demostrar que

$$(A + B)^2 \neq A^2 + 2AB + B^2$$

pero que en cambio

$$(A + B)^3 = A^3 + 3A^2B + 3AB^2 + B^3$$

Resultados

Al ser ambas matrices cuadradas se omitirá el comprobar si A y B son conmutables. Primero empezaremos con el primer caso. 

* $(A + B)^2 \neq A^2 + 2AB + B^2$
  
  Se comprueba el término de la izquierda del símbolo \neq
  
  $$A+B = \begin{pmatrix}
  0 & 1\\
  0 & 1
  \end{pmatrix} + \begin{pmatrix}
  -1 & -1\\
  0 & 0
  \end{pmatrix} = \begin{pmatrix}
  -1 & 0\\
  0 & 1
  \end{pmatrix}$$
  
  $$(A+B)^2 = \begin{pmatrix}
  -1 & 0\\
  0 & 1
  \end{pmatrix}\begin{pmatrix}
  -1 & 0\\
  0 & 1
  \end{pmatrix} = \begin{pmatrix}
  (-1)\cdot (-1) + 0\cdot 0 & (-1)\cdot 0 + 0\cdot 1\\
  0\cdot (-1) + 1\cdot 0 & 0\cdot 0 + 1\cdot 1
  \end{pmatrix} = \begin{pmatrix}
  1+0 & 0+0\\
  0+0 & 0+1
  \end{pmatrix} = \begin{pmatrix}
  1 & 0\\
  0 & 1
  \end{pmatrix}$$
  
  Ahora comprobaremos el valor de la suma de los términos de la derecha
  
  $$A^2 = \begin{pmatrix}
  0 & 1\\
  0 & 1
  \end{pmatrix}\begin{pmatrix}
  0 & 1\\
  0 & 1
  \end{pmatrix} = \begin{pmatrix}
  0\cdot 0 + 1\cdot 0 & 0\cdot 1 + 1\cdot 1\\
  0\cdot 0 + 1\cdot 0 & 0\cdot 1 + 1\cdot 1
  \end{pmatrix} = \begin{pmatrix}
  0+0 & 0+1\\
  0+0 & 0+1
  \end{pmatrix} = \begin{pmatrix}
  0 & 1\\
  0 & 1
  \end{pmatrix}$$
  
  $$2AB = 2\begin{pmatrix}
  0 & 1\\
  0 & 1
  \end{pmatrix}\begin{pmatrix}
  -1 & -1\\
  0 & 0
  \end{pmatrix} = 2\begin{pmatrix}
  0\cdot (-1) + 1\cdot 0 & 0\cdot (-1) + 1\cdot 0\\
  0\cdot (-1) + 1\cdot 0 & 0\cdot (-1) + 1\cdot 0
  \end{pmatrix} = 2\begin{pmatrix}
  0+0 & 0+0\\
  0+0 & 0+0
  \end{pmatrix} = 2\begin{pmatrix}
  0 & 0\\
  0 & 0
  \end{pmatrix}$$
  
  $$2AB = \begin{pmatrix}
  0 & 0\\
  0 & 0
  \end{pmatrix}$$
  
  $$B^2 = \begin{pmatrix}
  -1 & -1\\
  0 & 0
  \end{pmatrix}\begin{pmatrix}
  -1 & -1\\
  0 & 0
  \end{pmatrix} = \begin{pmatrix}
  (-1)\cdot (-1) + (-1)\cdot 0 & (-1)\cdot (-1) + (-1)\cdot 0\\
  0\cdot (-1) + 0\cdot 0       & 0\cdot (-1) + 0\cdot 0
  \end{pmatrix} = \begin{pmatrix}
  1 & 1\\
  0 & 0
  \end{pmatrix}$$
  
  $$A^2 + 2AB + B^2 = \begin{pmatrix}
  0 & 1\\
  0 & 1
  \end{pmatrix} + \begin{pmatrix}
  0 & 0\\
  0 & 0
  \end{pmatrix} + \begin{pmatrix}
  1 & 1\\
  0 & 0
  \end{pmatrix} = \begin{pmatrix}
  1 & 2\\
  0 & 1
  \end{pmatrix}$$
  
  En base a los procedimientos anteriores, podemos decir que
  
  $$(A+B)^2 \neq A^2 + 2AB + B^2$$
  
* $(A + B)^3 = A^3 + 3A^2B + 3AB^2 + B^3$

  Empezamos con el lado izquierdo de esta igualdad

  $$(A+B)^3 = (A+B)^2(A+B) = \begin{pmatrix}
  1 & 0\\
  0 & 1
  \end{pmatrix}\begin{pmatrix}
  -1 & 0\\
  0 & 1
  \end{pmatrix} = \begin{pmatrix}
  -1 & 0\\
  0 & 1
  \end{pmatrix}$$
  
  Comprobremos ahora que la expresión derecha es igual al izquierdo
  
  $$A^3 = A^2A = \begin{pmatrix}
  0 & 1\\
  0 & 1
  \end{pmatrix}\begin{pmatrix}
  0 & 1\\
  0 & 1
  \end{pmatrix} = \begin{pmatrix}
  0 & 1\\
  0 & 1
  \end{pmatrix}$$
  
  $$3A^2B = 3\begin{pmatrix}
  0 & 1\\
  0 & 1
  \end{pmatrix}\begin{pmatrix}
  -1 & -1\\
  0 & 0
  \end{pmatrix} = \begin{pmatrix}
  0\cdot (-1) + 1\cdot 0 & 0\cdot (-1) + 1\cdot 0\\
  0\cdot (-1) + 1\cdot 0 & 0\cdot (-1) + 1\cdot 0
  \end{pmatrix} = \begin{pmatrix}
  0+0 & 0+0\\
  0+0 & 0+0
  \end{pmatrix} = \begin{pmatrix}
  0 & 0\\
  0 & 0
  \end{pmatrix}$$
  
  $$3AB^2 = 3\begin{pmatrix}
  0 & 1\\
  0 & 1
  \end{pmatrix}\begin{pmatrix}
  1 & 1\\
  0 & 0
  \end{pmatrix} = \begin{pmatrix}
  0\cdot 1 + 1\cdot 0 & 0\cdot 1 + 1\cdot 0\\
  0\cdot 1 + 1\cdot 0 & 0\cdot 1 + 1\cdot 0
  \end{pmatrix} = \begin{pmatrix}
  0 & 0\\
  0 & 0
  \end{pmatrix}$$
  
  $$B^3 = B^2B = \begin{pmatrix}
  1 & 1\\
  0 & 0
  \end{pmatrix}\begin{pmatrix}
  -1 & -1\\
  0 & 0
  \end{pmatrix} = \begin{pmatrix}
  1\cdot (-1) + 1\cdot 0 & 1\cdot (-1) + 1\cdot 0\\
  0\cdot (-1) + 0\cdot 0 & 0\cdot (-1) + 0\cdot 0
  \end{pmatrix} = \begin{pmatrix}
  -1+0 & -1+0\\
  0+0 & 0+0
  \end{pmatrix} = \begin{pmatrix}
  -1 & -1\\
  0 & 0
  \end{pmatrix}$$
  
  $$A^3 + 3A^2B + 3AB^2 + B^3 = \begin{pmatrix}
  0 & 1\\
  0 & 1
  \end{pmatrix} + \begin{pmatrix}
  0 & 0\\
  0 & 0
  \end{pmatrix} + \begin{pmatrix}
  0 & 0\\
  0 & 0
  \end{pmatrix} + \begin{pmatrix}
  -1 & -1\\
  0 & 0
  \end{pmatrix} = \begin{pmatrix}
  -1 & 0\\
  0 & 1
  \end{pmatrix}$$
  
  Gracias al procedimiento anterior, es posible afirmar que $(A+B)^3 = A^3 + 3A^2B + 3AB^2 + B^3$


## Problema 6

Hallad las matrices $A$ y $B$ tales que cumplan las dos ecuaciones:

$$4A + 2B = \begin{pmatrix}
3 & 4 & 2\\
2 & 1 & 8
\end{pmatrix}$$

$$3A + B = \begin{pmatrix}
^3/_2 & 1 & 0\\
2 & ^1/_2 & 5
\end{pmatrix}$$

Respuestas

En este caso empezaremos despejando la matriz B en la segunda ecuación matricial

$$3A + B = \begin{pmatrix}
^3/_2 & 1 & 0\\
2 & ^1/_2 & 5
\end{pmatrix}\quad \Rightarrow \quad B = \begin{pmatrix}
^3/_2 & 1 & 0\\
2 & ^1/_2 & 5
\end{pmatrix} - 3A$$

Enseguida sustituimos el valor obtenido de B en la primera ecuación matricial

$$4A + 2B = \begin{pmatrix}
3 & 4 & 2\\
2 & 1 & 8
\end{pmatrix} \quad \Rightarrow \quad 4A + 2\Bigg(\begin{pmatrix}
^3/_2 & 1 & 0\\
2 & ^1/_2 & 5
\end{pmatrix} - 3A \Bigg) = \begin{pmatrix}
3 & 4 & 2\\
2 & 1 & 8
\end{pmatrix}$$

$$4A + 2\begin{pmatrix}
^3/_2 & 1 & 0\\
2 & ^1/_2 & 5
\end{pmatrix} - 2\cdot 3A = \begin{pmatrix}
3 & 4 & 2\\
2 & 1 & 8
\end{pmatrix}
\quad \Rightarrow \quad
4A + \begin{pmatrix}
3 & 2 & 0\\
4 & 1 & 10
\end{pmatrix} - 6A = \begin{pmatrix}
3 & 4 & 2\\
2 & 1 & 8
\end{pmatrix}$$

$$\begin{pmatrix}
3 & 2 & 0\\
4 & 1 & 10
\end{pmatrix} - 2A = \begin{pmatrix}
3 & 4 & 2\\
2 & 1 & 8
\end{pmatrix}
\quad \Rightarrow \quad
\begin{pmatrix}
3 & 2 & 0\\
4 & 1 & 10
\end{pmatrix} = \begin{pmatrix}
3 & 4 & 2\\
2 & 1 & 8
\end{pmatrix} + 2A$$

$$\begin{pmatrix}
3 & 2 & 0\\
4 & 1 & 10
\end{pmatrix} - \begin{pmatrix}
3 & 4 & 2\\
2 & 1 & 8
\end{pmatrix} = 2A
\quad \Rightarrow \quad
\begin{pmatrix}
0 & -2 & -2\\
2 & 0 & 2
\end{pmatrix} = 2A
\quad \Rightarrow \quad
A = \frac{1}{2}\begin{pmatrix}
0 & -2 & -2\\
2 & 0 & 2
\end{pmatrix}$$

$$A = \begin{pmatrix}
0 & -1 & -1\\
1 & 0 & 1
\end{pmatrix}$$

Ahora que sabemos al valor de A, por lo que podemos sustituir la A en la segunda ecuación

$$B = \begin{pmatrix}
^3/_2 & 1 & 0\\
2 & ^1/_2 & 5
\end{pmatrix} - 3\begin{pmatrix}
0 & -1 & -1\\
1 & 0 & 1
\end{pmatrix} = \begin{pmatrix}
^3/_2 & 1 & 0\\
2 & ^1/_2 & 5
\end{pmatrix} + \begin{pmatrix}
0 & 3 & 3\\
-3 & 0 & -3
\end{pmatrix} = \begin{pmatrix}
^3/_2 & 4 & 3\\
-1 & ^1/_2 & 2
\end{pmatrix}$$


## Problema 7

Sean $a,b,c \in \mathbb{R}$ y $A \in M_3(\mathbb{R})$ dada por

$$A = \begin{pmatrix}
a & a + b & a - c\\
a - b & b & b - c\\
a + b - 2 & c - b & c
\end{pmatrix}$$

¿Qué tienen que valer los parámetros para que $A$ sea?

* Triangular superior
  Para este caso, sabemos que $a_{ij} = 0 \quad i>j$, por ello. Las ecuaciones vistas en cada elemento abajo de la diagonal, las igualaremos a 0
  
  $$a-b=0 \qquad a+b-2=0 \qquad c-b=0$$
  $$a=b \qquad a+b=2 \qquad c=b$$
  $$a=b=c \qquad a+b=2 \qquad \Rightarrow \qquad a=b=c=1$$
  $$A = \begin{pmatrix}
  1 & 1 + 1 & 1 - 1\\
  1 - 1 & 1 & 1 - 1\\
  1 + 1 - 2 & 1 - 1 & 1
  \end{pmatrix} = A = \begin{pmatrix}
  1 & 2 & 0\\
  0 & 1 & 0\\
  0 & 0 & 1
  \end{pmatrix}$$
  
  
* Triangular inferior
  En este caso, sabemos que $a_{ij} = 0 \quad i<j$, por ello. Las ecuaciones vistas en cada elemento arriba de la diagonal, las igualaremos a 0
  
  $$a+b=0 \qquad a-c=0 \qquad b-c=0$$
  $$a=-b \qquad a=c \qquad b=c$$
  
  Con esto podemos dejar en claro la siguiente definición: $a=b=c$, que se contradice observamos que $a=-b$, puesto que $b \neq -b$
  
  De esta manera, decimos que no es posible conseguir una matriz triangular inferior con valores de $a,b,c \in \mathbb{R}$
  

* Simétrica

  Realizaremos el análisis con los términos de cada elemento de la matriz
  
  $$a-b=a+b \qquad a+b-2=a-c \qquad c-b=b-c$$
  $$-b=b \qquad b=2-c \qquad c+c=b+b $$
  $$-b=b \qquad b=2-c \qquad c=\frac{2}{2}b$$
  
  Gracias al despeje realizado, nos dimos cuenta que existen diversas contradicciones como al momento de igualar $b = -b$ puesto que no son iguales. Por lo que podemos decir que no hay valores para $a,b,c \in \mathbb{R}$


## Problema 8

Dada la matriz

$$A = \begin{pmatrix}
1 & 0\\
1 & 1
\end{pmatrix}$$

Calculad el valor de $A + A^2 + \dots + A^n$

para todo valor $n \geq 1$

Respuesta

Primero calcularemos la potencia $n$-ésima cuando $n=2$

$$A^2 = \begin{pmatrix}
1 & 0\\
1 & 1
\end{pmatrix}\begin{pmatrix}
1 & 0\\
1 & 1
\end{pmatrix} = \begin{pmatrix}
1\cdot 1 + 0\cdot 1 & 1\cdot 0 + 0\cdot 1\\
1\cdot 1 + 1\cdot 1 & 1\cdot 0 + 1\cdot 1
\end{pmatrix} = \begin{pmatrix}
1+0 & 0+0\\
1+1 & 0+1
\end{pmatrix} = \begin{pmatrix}
1 & 0\\
2 & 1
\end{pmatrix}$$

Hasta encontrar un patron seguimos obteniendo más potencias de A

$$A^3 = A^2 A = \begin{pmatrix}
1 & 0\\
2 & 1
\end{pmatrix}\begin{pmatrix}
1 & 0\\
1 & 1
\end{pmatrix} = \begin{pmatrix}
1\cdot 1 + 0\cdot 1 & 1\cdot 0 + 0\cdot 1\\
2\cdot 1 + 1\cdot 1 & 2\cdot 0 + 1\cdot 1
\end{pmatrix} = \begin{pmatrix}
1+0 & 0+0\\
2+1 & 0+1
\end{pmatrix} = \begin{pmatrix}
1 & 0\\
3 & 1
\end{pmatrix}$$

De esta manera inferimos que A^n se puede expresar como:

$$A^n = \begin{pmatrix}
1 & 0\\
n & 1
\end{pmatrix}$$

Para todo $n \geq 1$

Debido a que la operación a realizar es una sumatoria, el resultado de esta quedaría de la siguiente forma

$$A + A^2 + \cdots + A^n = \begin{pmatrix}
n & 0\\
\frac{n(n+1)}{2} & n
\end{pmatrix}$$


## Problema 9

Sea $A$ una matriz cuadrada de orden $n$, $A \in M_n(\mathbb{K})$. Decimos que $B$ es una raíz cuadrada de $A$ si $B^2 = A$

* Halla tres raices cuadradas diferentes de $I_2$ (Matriz identidad de orden $2$)
* Demuestra que la matriz $\bigl(\begin{smallmatrix} 0&1 \\ 0&0 \end{smallmatrix} \bigr)$ no tiene raíces cuadradas

Respuestas

Raíces de $I_2$

Lo primero a realizar será analizar el procedimiento de elevar al cuadrado una matriz cuyo resultado es una matriz identidad de orden $2$. Esto es así para tomar en cuenta las      condiciones necesarias para que los valores de cada elemento de la matriz que resulte raíz de $I_2$ sean los correctos.
  
  Se exprasará dicho procedimiento de la siguiente forma
  
  $$B^2 = \begin{pmatrix}
  a & b\\
  c & d
  \end{pmatrix}\begin{pmatrix}
  a & b\\
  c & d
  \end{pmatrix}$$
  
  $$b_{11} = a\cdot a + b\cdot c = 1 \qquad b_{12} = a\cdot b + b\cdot d = 0 \qquad b_{21} = c\cdot a + d\cdot c = 0 \qquad b_{22} = c\cdot b + d\cdot d = 1$$

A partir de cada ecuación, es posible definir casos distintos para determinar todas las raíces posibles para la matriz identidad

Un primer caso sería que se cumpliera que $a$ fuese el opuesto de $d$ o viceversa, Además de cumplir que el producto $bc$ se despeje y así obtener los factores que serán valores para $b$ y $c$

$$a = -d \qquad bc = 1-a\cdot a$$
Otro caso posible es el de considerar el producto $bc$ igual a $1$, mientras que $a$ y $d$ se mantienen nulos. De esta manera, la búsqueda se reduce a buscar dos factores que al multiplicarlos den 1.

$$bc = 1 \qquad d = a = 0$$

Hay que tener en cuenta la comprobación de los valores que asignemos a cada elemento, para que las ecuaciones mantengan la igualdad.

Ahora procederemos a proponer raíces de $I_2$

* Primer ejemplo
  
  $$B = \begin{pmatrix}
  -5 & -8\\
  3 & 5
  \end{pmatrix} \qquad B^2 = \begin{pmatrix}
  -5 & -8\\
  3 & 5
  \end{pmatrix}\begin{pmatrix}
  -5 & -8\\
  3 & 5
  \end{pmatrix} = \begin{pmatrix}
  (-5)\cdot (-5) + (-8)\cdot 3 & (-5)\cdot (-8) + (-8)\cdot 5\\
  3\cdot (-5) + 5\cdot 3 & 3\cdot (-8) + 5\cdot 5
  \end{pmatrix}$$
  
  $$B^2 = \begin{pmatrix}
  25-24 & 40-40\\
  -15+15 & -24+25
  \end{pmatrix} = \begin{pmatrix}
  1 & 0\\
  0 & 1
  \end{pmatrix}$$

* Segundo ejemplo
  
  $$B = \begin{pmatrix}
  0 & \sqrt{1}\\
  \sqrt{1} & 0
  \end{pmatrix} \qquad B^2 = \begin{pmatrix}
  0 & \sqrt{1}\\
  \sqrt{1} & 0
  \end{pmatrix} \begin{pmatrix}
  0 & \sqrt{1}\\
  \sqrt{1} & 0
  \end{pmatrix} = \begin{pmatrix}
  0\cdot 0 + \sqrt{1}\cdot \sqrt{1} & 0\cdot \sqrt{1} + \sqrt{1}\cdot 0\\
  \sqrt{1}\cdot 0 + 0\cdot \sqrt{1} & \sqrt{1}\cdot \sqrt{1} + 0\cdot 0
  \end{pmatrix}$$
  
  $$B^2 = \begin{pmatrix}
  0+1 & 0+0\\
  0+0 & 1+0
  \end{pmatrix} = \begin{pmatrix}
  1 & 0\\
  0 & 1
  \end{pmatrix}$$
  
* Tercer ejemplo
  
  $$B = \begin{pmatrix}
  0 & ^1/_2\\
  2 & 0
  \end{pmatrix} \qquad B^2 = \begin{pmatrix}
  0 & ^1/_2\\
  2 & 0
  \end{pmatrix} \begin{pmatrix}
  0 & ^1/_2\\
  2 & 0
  \end{pmatrix} = \begin{pmatrix}
  0\cdot 0 + ^1/_2\cdot 2 & 0\cdot ^1/_2 + ^1/_2\cdot 0\\
  2\cdot 0 + 0\cdot 2 & 2\cdot ^1/_2 + 0\cdot 0
  \end{pmatrix}$$
  
  $$B^2 = \begin{pmatrix}
  0+1 & 0+0\\
  0+0 & 1+0
  \end{pmatrix} = \begin{pmatrix}
  1 & 0\\
  0 & 1
  \end{pmatrix}$$
  
El segundo punto a tratar en este problema es demostrar que $\bigl(\begin{smallmatrix} 0&1 \\ 0&0 \end{smallmatrix} \bigr)$ no tiene raícies cuadradas
  
Para ello tomaremos el razonamiento expuesto con anterioridad. A continuación se mostrará las ecuaciones que permitiran analizar los procedimientos.
  
$$B = \begin{pmatrix}
a & b\\
c & d
\end{pmatrix} \qquad B^2 = \begin{pmatrix}
a & b\\
c & d
\end{pmatrix} \begin{pmatrix}
a & b\\
c & d
\end{pmatrix}$$
  
$$b_{11} = a\cdot a + b\cdot c = 0 \qquad b_{12} = a\cdot b + b\cdot d = 1 \qquad b_{21} = c\cdot a + d\cdot c = 0 \qquad b_{22} = c\cdot b + d\cdot d = 0$$
En la  tercer ecuación es posible despejar $c$ como $(a+d)c = 0 \Rightarrow c = 0$. El valor nulo de $c$ hace posible despejar $a$ y  $d$ en la primera y cuarta ecuación
  
$$a\cdot a + 0 = 0 \quad \Rightarrow \quad a^2=0 \quad \Rightarrow \quad a=0$$
El mismo caso se repite para d. Así, al momento de comprobar la segunda ecuación.Obtenemos una contradicción
  
$$a\cdot b + b\cdot d = 1 \quad \Rightarrow \quad 0\cdot b + b\cdot 0 = 1 \quad \Rightarrow \quad 0 = 1$$
  
Por ello, podemos afirmar que la matriz $\bigl(\begin{smallmatrix} 0&1 \\ 0&0 \end{smallmatrix} \bigr)$ carece de una raíz cuadrada

## Problema 10

Halla todas las matrices con coeficientes en $\mathbb{R}$ que conmutan con la matriz

$$A = \begin{pmatrix}
0 & 0 & 0\\
1 & 0 & 0\\
1 & 1 & 0
\end{pmatrix}$$

Resultados

Para poder determinar que tipo de matrices pueden conmutar con la matriz $A$, haremos alusión a una matriz $B$ que se suponga tenga esta propiedad.

$$B = \begin{pmatrix}
b_{11} & b_{12} & b_{13}\\
b_{21} & b_{22} & b_{23}\\
b_{31} & b_{32} & b_{33}
\end{pmatrix}$$

$$AB = \begin{pmatrix}
0 & 0 & 0\\
1 & 0 & 0\\
1 & 1 & 0
\end{pmatrix}\begin{pmatrix}
b_{11} & b_{12} & b_{13}\\
b_{21} & b_{22} & b_{23}\\
b_{31} & b_{32} & b_{33}
\end{pmatrix} = \begin{pmatrix}
0\cdot b_{11} + 0\cdot b_{21} + 0\cdot b_{31} & 0\cdot b_{12} + 0\cdot b_{22} + 0\cdot b_{32} & 0\cdot b_{13} + 0\cdot b_{23} + 0\cdot b_{33}\\
1\cdot b_{11} + 0\cdot b_{21} + 0\cdot b_{31} & 1\cdot b_{12} + 0\cdot b_{22} + 0\cdot b_{32} & 1\cdot b_{13} + 0\cdot b_{23} + 0\cdot b_{33}\\
1\cdot b_{11} + 1\cdot b_{21} + 0\cdot b_{31} & 1\cdot b_{12} + 1\cdot b_{22} + 0\cdot b_{32} & 1\cdot b_{13} + 1\cdot b_{23} + 0\cdot b_{33} 
\end{pmatrix}$$

$$AB = \begin{pmatrix}
0+0+0 & 0+0+0 & 0+0+0\\
b_{11}+0+0 & b_{12}+0+0 & b_{13}+0+0\\
b_{11}+b_{21}+0 & b_{12}+b_{22}+0 & b_{13}+b_{23}+0
\end{pmatrix} = \begin{pmatrix}
0 & 0 & 0\\
b_{11} & b_{12} & b_{13}\\
b_{11}+b_{21} & b_{12}+b_{22} & b_{13}+b_{23}
\end{pmatrix}$$

$$BA = \begin{pmatrix}
b_{11} & b_{12} & b_{13}\\
b_{21} & b_{22} & b_{23}\\
b_{31} & b_{32} & b_{33}
\end{pmatrix}\begin{pmatrix}
0 & 0 & 0\\
1 & 0 & 0\\
1 & 1 & 0
\end{pmatrix} = \begin{pmatrix}
b_{11}\cdot 0 + b_{12}\cdot 1 + b_{13}\cdot 1 & b_{11}\cdot 0 + b_{12}\cdot 0 + b_{13}\cdot 1 & b_{11}\cdot 0 + b_{12}\cdot 0 + b_{13}\cdot 0\\
b_{21}\cdot 0 + b_{22}\cdot 1 + b_{23}\cdot 1 & b_{21}\cdot 0 + b_{22}\cdot 0 + b_{23}\cdot 1 & b_{21}\cdot 0 + b_{22}\cdot 0 + b_{23}\cdot 0\\
b_{31}\cdot 0 + b_{32}\cdot 1 + b_{33}\cdot 1 & b_{31}\cdot 0 + b_{32}\cdot 0 + b_{33}\cdot 1 & b_{31}\cdot 0 + b_{32}\cdot 0 + b_{33}\cdot 0
\end{pmatrix}$$

$$BA = \begin{pmatrix}
0+b_{12}+b_{13} & 0+0+b_{13} & 0+0+0\\
0+b_{22}+b_{23} & 0+0+b_{23} & 0+0+0\\
0+b_{32}+b_{33} & 0+0+b_{33} & 0+0+0
\end{pmatrix} = \begin{pmatrix}
b_{12}+b_{13} & b_{13} & 0\\
b_{22}+b_{23} & b_{23} & 0\\
b_{32}+b_{33} & b_{33} & 0
\end{pmatrix}$$

Como decimos que ambas matrices son conmutativas, lo expresaremos de la siguiente forma.

$$AB = BA \qquad \Rightarrow \qquad \begin{pmatrix}
0 & 0 & 0\\
b_{11} & b_{12} & b_{13}\\
b_{11}+b_{21} & b_{12}+b_{22} & b_{13}+b_{23}
\end{pmatrix} = \begin{pmatrix}
b_{12}+b_{13} & b_{13} & 0\\
b_{22}+b_{23} & b_{23} & 0\\
b_{32}+b_{33} & b_{33} & 0
\end{pmatrix}$$

Ahora igualaremos a todo elemento de ambas matrices, en la misma posición.

$$b_{12} + b_{13} = 0 \qquad b_{13} = 0 \qquad b_{13}+b_{23} = 0 \qquad \implies \qquad b_{12} = 0 \qquad b_{13} = 0 \qquad b_{23} = 0$$
$$b_{11} = b_{22} + b_{23} \qquad b_{12} = b_{23} \qquad b_{11}+b_{21}=b_{32}+b_{33} \qquad b_{12}+b_{22} = b_{33} \qquad \implies$$

$$b_{11} = b_{22} = b_{33} = x \qquad b_{21} = b_{32} = y$$

Consideraremos a $b_{31} = z$

Por lo que expresamos el resultado de la siguiente manera. La matriz $B \in M_3\mathbb{R}$ es conmutativa con la matriz $A$, con $a,b,z \in \mathbb{R}$

$$B = \begin{pmatrix}
x & 0 & 0\\
y & x & 0\\
z & y & x
\end{pmatrix}$$


## Problema 11

Halla las potencias $n$-ésimas de las matrices

$$A = \begin{pmatrix}
0 & 1 & 0\\
0 & 0 & 1\\
0 & 0 & 0
\end{pmatrix} \qquad B = \begin{pmatrix}
1 & 1 & 1\\
1 & 1 & 1\\
1 & 1 & 1
\end{pmatrix}$$

Respuestas

En ambos casos obtendremos algunas potencias para observar como actuán estas matrices al multiplicarse por si mismas.

* A
  
  $$A^2 = \begin{pmatrix}
  0 & 1 & 0\\
  0 & 0 & 1\\
  0 & 0 & 0
  \end{pmatrix} \begin{pmatrix}
  0 & 1 & 0\\
  0 & 0 & 1\\
  0 & 0 & 0
  \end{pmatrix} = \begin{pmatrix}
  0\cdot 0 + 1\cdot 0 + 0\cdot 0 & 0\cdot 1 + 1\cdot 0 + 0\cdot 0 & 0\cdot 0 + 1\cdot 1 + 0\cdot 0\\
  0\cdot 0 + 0\cdot 0 + 1\cdot 0 & 0\cdot 1 + 0\cdot 0 + 1\cdot 0 & 0\cdot 0 + 0\cdot 1 + 1\cdot 0\\
  0\cdot 0 + 0\cdot 0 + 0\cdot 0 & 0\cdot 1 + 0\cdot 0 + 0\cdot 0 & 0\cdot 0 + 0\cdot 1 + 0\cdot 0
  \end{pmatrix}$$

  $$A^2 = \begin{pmatrix}
  0+0+0 & 0+0+0 & 0+1+0\\
  0+0+0 & 0+0+0 & 0+0+0\\
  0+0+0 & 0+0+0 & 0+0+0
  \end{pmatrix} = \begin{pmatrix}
  0 & 0 & 1\\
  0 & 0 & 0\\
  0 & 0 & 0
  \end{pmatrix}$$
  
  $$A^3 = A^2 A = \begin{pmatrix}
  0 & 0 & 1\\
  0 & 0 & 0\\
  0 & 0 & 0
  \end{pmatrix} \begin{pmatrix}
  0 & 1 & 0\\
  0 & 0 & 1\\
  0 & 0 & 0
  \end{pmatrix} = \begin{pmatrix}
  0\cdot 0 + 0\cdot 0 + 1\cdot 0 & 0\cdot 1 + 0\cdot 0 + 1\cdot 0 & 0\cdot 0 + 0\cdot 1 + 1\cdot 0\\
  0\cdot 0 + 0\cdot 0 + 0\cdot 0 & 0\cdot 1 + 0\cdot 0 + 0\cdot 0 & 0\cdot 0 + 0\cdot 1 + 0\cdot 0\\
  0\cdot 0 + 0\cdot 0 + 0\cdot 0 & 0\cdot 1 + 0\cdot 0 + 0\cdot 0 & 0\cdot 0 + 0\cdot 1 + 0\cdot 0
  \end{pmatrix}$$
  
  $$A^3 = \begin{pmatrix}
  0 & 0 & 0\\
  0 & 0 & 0\\
  0 & 0 & 0
  \end{pmatrix}$$
  
  A partir de la potencia al cubo, el resultado siempre sera una matriz nula, por ello el valor de $A^n$ es
  
  $$A^n = \begin{pmatrix}
  0 & 0 & 0\\
  0 & 0 & 0\\
  0 & 0 & 0
  \end{pmatrix} \qquad \text{si y solo si} \qquad n > 2$$
  
  
* B
  
  $$B^2 = \begin{pmatrix}
  1 & 1 & 1\\
  1 & 1 & 1\\
  1 & 1 & 1
  \end{pmatrix} \begin{pmatrix}
  1 & 1 & 1\\
  1 & 1 & 1\\
  1 & 1 & 1
  \end{pmatrix} = \begin{pmatrix}
  1\cdot 1 + 1\cdot 1 + 1\cdot 1 & 1\cdot 1 + 1\cdot 1 + 1\cdot 1 & 1\cdot 1 + 1\cdot 1 + 1\cdot 1\\
  1\cdot 1 + 1\cdot 1 + 1\cdot 1 & 1\cdot 1 + 1\cdot 1 + 1\cdot 1 & 1\cdot 1 + 1\cdot 1 + 1\cdot 1\\
  1\cdot 1 + 1\cdot 1 + 1\cdot 1 & 1\cdot 1 + 1\cdot 1 + 1\cdot 1 & 1\cdot 1 + 1\cdot 1 + 1\cdot 1
  \end{pmatrix}$$
  
  $$B^2 = \begin{pmatrix}
  1+1+1 & 1+1+1 & 1+1+1\\
  1+1+1 & 1+1+1 & 1+1+1\\
  1+1+1 & 1+1+1 & 1+1+1
  \end{pmatrix} = \begin{pmatrix}
  3 & 3 & 3\\
  3 & 3 & 3\\
  3 & 3 & 3\\
  \end{pmatrix}$$
  
  $$B^3 = B^2 B = \begin{pmatrix}
  3 & 3 & 3\\
  3 & 3 & 3\\
  3 & 3 & 3\\
  \end{pmatrix} \begin{pmatrix}
  1 & 1 & 1\\
  1 & 1 & 1\\
  1 & 1 & 1
  \end{pmatrix} = \begin{pmatrix}
  3\cdot 1 + 3\cdot 1 + 3\cdot 1 & 3\cdot 1 + 3\cdot 1 + 3\cdot 1 & 3\cdot 1 + 3\cdot 1 + 3\cdot 1\\
  3\cdot 1 + 3\cdot 1 + 3\cdot 1 & 3\cdot 1 + 3\cdot 1 + 3\cdot 1 & 3\cdot 1 + 3\cdot 1 + 3\cdot 1\\
  3\cdot 1 + 3\cdot 1 + 3\cdot 1 & 3\cdot 1 + 3\cdot 1 + 3\cdot 1 & 3\cdot 1 + 3\cdot 1 + 3\cdot 1
  \end{pmatrix}$$
  
  $$B^2 = \begin{pmatrix}
  3+3+3 & 3+3+3 & 3+3+3\\
  3+3+3 & 3+3+3 & 3+3+3\\
  3+3+3 & 3+3+3 & 3+3+3
  \end{pmatrix} = \begin{pmatrix}
  9 & 9 & 9\\
  9 & 9 & 9\\
  9 & 9 & 9\\
  \end{pmatrix}$$
  
  Ahora es posible definir la potencia $n$-ésima de B
  
  $$B^n = \begin{pmatrix}
  3^{n-1} & 3^{n-1} & 3^{n-1}\\
  3^{n-1} & 3^{n-1} & 3^{n-1}\\
  3^{n-1} & 3^{n-1} & 3^{n-1}
  \end{pmatrix}$$
  


## Problema 12

Sean $A, B \in M_n(\mathbb{R})$ dos matrices tales que $A$ es simétrica y $B$ es antisimétrica.

Demostrad que $AB + BA$ es antisimétrica y que $AB − BA$ es simétrica

Respuestas

Para comenzar se nos aclara al inicio del planteo, que la matriz $A$ es simétrica, en otras palabras, $A = A^t$.

Por otro lado, B se dmenciona como antisimétrica, lo cual quiere decir que $B^t = -B$

Primero, se demostrará que el resultado de $AB + BA$ es una matriz antisimétrica. De esta manera, podemos expresar esto como

$$(AB + BA)^t = -(AB+BA)$$

Para determinar si es cierta o no, desarrollamos la parte izquierda, con ayuda de las propiedades de las matrices transpuestas

$$(AB)^t + (BA)^t = -(AB + BA)$$
$$B^t A^t + A^t B^t = -(AB + BA)$$

$$-BA + (-AB) = -(AB + BA)$$
$$-(BA + AB) = -(AB + BA)  \qquad \Rightarrow \qquad -(AB + BA) = -(AB + BA)$$
Al final, apreciamos que la igualdad se cumple, de manera que $AB+BA$ 

Ahora, pasemos al siguiente caso, el cual consiste en demostrar que $AB - BA$ es una matriz simétrica. Pasemos a reflejar en una expresión lo que se probará como cierto

$$(AB - BA)^t = AB - BA$$
$$(AB)^t - (BA)^t = AB - BA$$

$$B^t A^t - A^t B^t = AB - BA$$
$$-BA - (-AB) = AB - BA$$
$$-BA + AB = AB - BA \qquad \Rightarrow \qquad AB - BA = AB - BA$$

De esta manera demostramos que el resultado de $AB-BA$ es una matriz simétrica


## Problema 13

Sea $A$ una matriz cuadrada de orden $n$. Demostrad que:

* $A + A^t$ es simétrica
* $A − A^t$ es antisimétrica
* $A$ se puede poner siempre como suma de una matriz simétrica y una antisimétrica


Resultados

* $A + A^t$ es simétrica
  
  Si dicha matriz es simétrica. Es posible expresarla de la siguiente manera
  
  $$(A + A^t)^t = A + A^t \qquad \Rightarrow \qquad A^t + (A^t)^t = A + A^t$$
  $$A^t + A = A + A^t \qquad \Rightarrow \qquad A + A^t = A + A^t$$
  
  De esta manera demostramos que la matriz resultante de la suma de $A$ y $A^t$ es simétrica
  
* $A − A^t$ es antisimétrica

  Dicha afirmación se expresa de la siguiente forma
  
  $$(A - A^t)^t = -(A - A^t) \qquad \Rightarrow \qquad A^t - (A^t)^t = -(A-A^t)$$
  $$A^t - A = -(A-A^t) \qquad \Rightarrow \qquad -(A -A^t) = -(A-A^t)$$
  
  Por lo tanto, la matriz $A - A^t$ es antisimétrica
  
* $A$ es igual a la suma de una matriz simétrica y otra antisimétrica

  Para proceder usaremos la matriz simétrica y la antisimétrica anteriormente comprobadas
  
  $$A = \frac{1}{2}(2A) \qquad \Rightarrow \qquad A = \frac{1}{2}(2A) + \frac{1}{2}(A^t) - \frac{1}{2}(A^t)$$
  
  $$A = \frac{1}{2}(A+A) + \frac{1}{2}(A^t) - \frac{1}{2}(A^t) \qquad \Rightarrow \qquad \frac{1}{2}(A) + \frac{1}{2}(A) + \frac{1}{2}(A^t) - \frac{1}{2}(A^t)$$
  
  $$A = \frac{1}{2}(A+A^t) + \frac{1}{2}(A-A^t) \qquad \Rightarrow \qquad A = \frac{1}{2} \big( (A+A^t) + (A-A^t) \big)$$
  Así demostramos que la suma de una matriz simétrica y una antisimátrica da como resultado A

## Problema 14

Sean $A$ y $B$ matrices cuadradas de orden $n$ de modo que $B$ es simétrica. Demostrad que:

* $AA^t$ es simétrica
* $ABA^t$ es simétrica
* Si $A$ es antisimétrica, entonces $A^2$ es simétrica
* Si $A^2 = 0$, entonces $A(A + I_n)^i = A \quad \forall i = 0, 1, 2, \dots$

Resultados 

* $AA^t$ es simétrica

  $$(AA^t)^t = AA^t \qquad \Rightarrow \qquad (A^t)^tA^t = AA^t \qquad \Rightarrow \qquad AA^t = AA^t$$
  
* $ABA^t$ es simétrica

  $$(ABA^t)^t = ABA^t \qquad \Rightarrow \qquad (A^t)^tB^tA^t = ABA^t \qquad \Rightarrow \qquad ABA^t = ABA^t$$
  
* Si $A$ es antisimétrica, entonces $A^2$ es simétrica
  
  El enunciado aclara que $A$ es antisimétrica, por lo que podemos decir que $A^t = -A$
  
  $$(A^2)^t = A^2 \qquad \Rightarrow \qquad (AA)^t = AA \qquad \Rightarrow \qquad  A^tA^t = AA \qquad \Rightarrow \qquad (-A)(-A) = AA $$
  
  $$(-1)(-1)AA = AA \qquad \Rightarrow \qquad AA = AA$$
  
* Si $A^2 = 0$, entonces $A(A + I_n)^i = A \quad \forall i = 0, 1, 2, \dots$

  Usaremos los primeros elementos de $i$ para poder conocer el comportamiento de la igualdad y así demostrar si $A(A + I_n)^i = A$

  * $i=0$
    $$A(A + I_n)^0 = A \qquad \Rightarrow \qquad AI_n = A \qquad \Rightarrow \qquad A = A$$
  
  * $i=1$
    $$A(A + I_n)^1 = A \qquad \Rightarrow \qquad AA + AI_n = A \qquad \Rightarrow \qquad A^2 + A = A \qquad \Rightarrow \qquad A = A$$
  
  * $i=2$
    $$A(A + I_n)^2 = A \qquad \Rightarrow \qquad A(A + I_n)(A + I_n) = A \qquad \Rightarrow \qquad A(A^2 + 2AI_n + I_n^2)=A$$
    
    $$A(2A + I_n)=A \qquad \Rightarrow \qquad 2A^2 + I_nA=A \qquad \Rightarrow \qquad 2\cdot 0 + A=A \qquad \Rightarrow \qquad A=A$$
  
  De esta manera demostramos que la igualdad se cumple satisfactoriamente

## Problema 15

Una matriz $A \in M_n(\mathbb{R})$ se llama estocástica si:

* Todos sus coeficientes son no negativos, es decir $a_{ij} \geq 0$ para todo $i, j = 1, 2, \dots, n$
* La suma de los coeficientes de cada fila vale $1$, es decir

$$\displaystyle\sum_{j=1}^{n} a_{ij} = 1 \quad \forall i = 1, \dots, n$$

Diremos que una matriz es doblemente estocástica si además la suma de los coeficientes de cada columna también vale $1$, es decir, si $\sum_{i=1}^n a_{ij} \quad \forall j = 1, \dots, n$

* Da un ejemplo de matriz $A \in M_4(\mathbb{R})$ estocástica
* Da un ejemplo de matriz $A \in M_4(\mathbb{R})$ doblemente estocástica
* Da un ejemplo de matriz estocástica y simétrica

Resultados

* Matriz $A \in M_4(\mathbb{R})$ estocástica
  
  $$A = \begin{pmatrix}
  ^1/_4 & ^1/_8 & ^1/_8 & ^1/_2\\
  ^3/_7 & ^3/_7 & ^1/_{14} & ^1/_{14}\\
  ^3/_9 & ^1/_3 & ^1/_6 & ^1/_6\\
  ^1/_5 & ^3/_5 & ^1/_{10} & ^1/_{10}\\
  \end{pmatrix}$$
  
* Matriz $A \in M_4(\mathbb{R})$ doblemente estocástica

  $$A = \begin{pmatrix}
  ^1/_4 & ^1/_2 & ^1/_8 & ^1/_8\\
  ^3/_8 & ^1/_8 & ^3/_{10} & ^1/_5\\
  ^1/_8 & ^1/_8 & ^3/_8 & ^3/_8\\
  ^1/_4 & ^1/_4 & ^1/_5 & ^3/_{10}\\
  \end{pmatrix}$$
  
* Matriz estocástica simétrica

  $$A = \begin{pmatrix}
  ^1/_2 & ^1/_4 & ^1/_8 & ^1/_8\\
  ^1/_4 & ^1/_3 & ^1/_6 & ^1/_4\\
  ^1/_8 & ^1/_6 & ^2/_6 & ^3/_8\\
  ^1/_8 & ^1/_4 & ^3/_8 & ^1/_4\\
  \end{pmatrix}$$


## Problema 16

Consideramos la matriz

$$A = \begin{pmatrix}
0 & a & a^2 & a^3\\
0 & 0 & a & a^2\\
0 & 0 & 0 & a\\
0 & 0 & 0 & 0
\end{pmatrix}$$

A partir de ella definimos la matriz $B$ como

$$B = A - \frac{1}{2}A^2 + \frac{1}{3}A^3 - \frac{1}{4}A^4 + \dots$$

Demostrad que es este sumatorio solamente hay un número finito de términos no nulos y calculad $B$.

Demostrad también que el sumatorio

$$B + \frac{1}{2!}B^2 + \frac{1}{3!}B^3 + \frac{1}{4!}B^4 + \dots$$

solamente tiene un número finito de términos no nulos y que su suma vale $A$

Resultados

Para demostrar el primer punto mencionado, hareremos las potencias de $A$ para saber como cambian estas

$$A^2 = \begin{pmatrix}
0 & a & a^2 & a^3\\
0 & 0 & a & a^2\\
0 & 0 & 0 & a\\
0 & 0 & 0 & 0
\end{pmatrix} \begin{pmatrix}
0 & a & a^2 & a^3\\
0 & 0 & a & a^2\\
0 & 0 & 0 & a\\
0 & 0 & 0 & 0
\end{pmatrix} = \begin{pmatrix}
0 & 0 & a^2 & 2a^3\\
0 & 0 & 0 & a^2\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0
\end{pmatrix}$$

$$A^3 = A^2A = \begin{pmatrix}
0 & 0 & a^2 & 2a^3\\
0 & 0 & 0 & a^2\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0
\end{pmatrix} \begin{pmatrix}
0 & a & a^2 & a^3\\
0 & 0 & a & a^2\\
0 & 0 & 0 & a\\
0 & 0 & 0 & 0
\end{pmatrix} = \begin{pmatrix}
0 & 0 & 0 & a^3\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0
\end{pmatrix}$$

$$A^4 = A^3A = \begin{pmatrix}
0 & 0 & 0 & a^3\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0
\end{pmatrix} \begin{pmatrix}
0 & a & a^2 & a^3\\
0 & 0 & a & a^2\\
0 & 0 & 0 & a\\
0 & 0 & 0 & 0
\end{pmatrix} = \begin{pmatrix}
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & a\\
0 & 0 & 0 & 0
\end{pmatrix}$$

Desde A^4, los resultados de elevar la matriz $A$ se vuelven nulos, decimos que $A^n = 0 \quad \text{si} \quad n \geq 4$. De esta manera nos damos cuenta que la sumatoria tiene un número finito de elementos no nulos. Procederemos a obtener B

$$B = A - \frac{1}{2}A^2 + \frac{1}{3}A^3 = \begin{pmatrix}
0 & a & a^2 & a^3\\
0 & 0 & a & a^2\\
0 & 0 & 0 & a\\
0 & 0 & 0 & 0
\end{pmatrix} - \frac{1}{2}\begin{pmatrix}
0 & 0 & a^2 & 2a^3\\
0 & 0 & 0 & a^2\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0
\end{pmatrix} + \frac{1}{3}\begin{pmatrix}
0 & 0 & 0 & a^3\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0
\end{pmatrix}$$

$$B = \begin{pmatrix}
0 & a & a^2 & a^3\\
0 & 0 & a & a^2\\
0 & 0 & 0 & a\\
0 & 0 & 0 & 0
\end{pmatrix} - \begin{pmatrix}
0 & 0 & \frac{1}{2} a^2 & a^3\\
0 & 0 & 0 & \frac{1}{2} a^2\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0
\end{pmatrix} + \begin{pmatrix}
0 & 0 & 0 & \frac{1}{3} a^3\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0
\end{pmatrix}$$

$$B = \begin{pmatrix}
0 & a & \frac{1}{2} a^2 & 0\\
0 & 0 & a & \frac{1}{2} a^2\\
0 & 0 & 0 & a\\
0 & 0 & 0 & 0
\end{pmatrix} + \begin{pmatrix}
0 & 0 & 0 & \frac{1}{3} a^3\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0
\end{pmatrix} = \begin{pmatrix}
0 & a & \frac{1}{2} a^2 & \frac{1}{3} a^3\\
0 & 0 & a & \frac{1}{2} a^2\\
0 & 0 & 0 & a\\
0 & 0 & 0 & 0
\end{pmatrix}$$

Una vez obtenido $B$, demostraremos el segundo punto que es la sumatoria de $B$. Como hicimos anteriormente, obtendremos las potencias de la matriz.

$$B^2 = \begin{pmatrix}
0 & a & \frac{1}{2} a^2 & \frac{1}{3} a^3\\
0 & 0 & a & \frac{1}{2} a^2\\
0 & 0 & 0 & a\\
0 & 0 & 0 & 0
\end{pmatrix} \begin{pmatrix}
0 & a & \frac{1}{2} a^2 & \frac{1}{3} a^3\\
0 & 0 & a & \frac{1}{2} a^2\\
0 & 0 & 0 & a\\
0 & 0 & 0 & 0
\end{pmatrix} = \begin{pmatrix}
0 & 0 & a^2 & a^3\\
0 & 0 & 0 & a^2\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0
\end{pmatrix}$$

$$A^3 = B^2B = \begin{pmatrix}
0 & 0 & a^2 & a^3\\
0 & 0 & 0 & a^2\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0
\end{pmatrix} \begin{pmatrix}
0 & a & \frac{1}{2} a^2 & \frac{1}{3} a^3\\
0 & 0 & a & \frac{1}{2} a^2\\
0 & 0 & 0 & a\\
0 & 0 & 0 & 0
\end{pmatrix} = \begin{pmatrix}
0 & 0 & 0 & a^3\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0
\end{pmatrix}$$

$$A^4 = B^3B = \begin{pmatrix}
0 & 0 & 0 & a^3\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0
\end{pmatrix} \begin{pmatrix}
0 & a & \frac{1}{2} a^2 & \frac{1}{3} a^3\\
0 & 0 & a & \frac{1}{2} a^2\\
0 & 0 & 0 & a\\
0 & 0 & 0 & 0
\end{pmatrix} = \begin{pmatrix}
0 & a & 0 & 0\\
0 & 0 & a & 0\\
0 & 0 & 0 & a\\
0 & 0 & 0 & 0
\end{pmatrix}$$

A partir de la cuarta potencia: $B^n = 0 \quad \text{si} \quad n \geq 4$. La sumatoria tiene una cantidad finita de términos no nulos, como se quiere demostrar. Pasaremos a demostrar que la sumatoria siguiente es igual a la matriz $A$

$$C=B + \frac{1}{2!}B^2 + \frac{1}{3!}B^3 = \begin{pmatrix}
0 & a & \frac{1}{2} a^2 & \frac{1}{3} a^3\\
0 & 0 & a & \frac{1}{2} a^2\\
0 & 0 & 0 & a\\
0 & 0 & 0 & 0
\end{pmatrix} + \frac{1}{2!} \begin{pmatrix}
0 & 0 & a^2 & a^3\\
0 & 0 & 0 & a^2\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0
\end{pmatrix} + \frac{1}{3!} \begin{pmatrix}
0 & 0 & 0 & a^3\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0
\end{pmatrix}$$

$$C = \begin{pmatrix}
0 & a & \frac{1}{2} a^2 & \frac{1}{3} a^3\\
0 & 0 & a & \frac{1}{2} a^2\\
0 & 0 & 0 & a\\
0 & 0 & 0 & 0
\end{pmatrix} + \frac{1}{2} \begin{pmatrix}
0 & 0 & a^2 & a^3\\
0 & 0 & 0 & a^2\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0
\end{pmatrix} + \frac{1}{6} \begin{pmatrix}
0 & 0 & 0 & a^3\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0
\end{pmatrix}$$

$$C = \begin{pmatrix}
0 & a & \frac{1}{2} a^2 & \frac{1}{3} a^3\\
0 & 0 & a & \frac{1}{2} a^2\\
0 & 0 & 0 & a\\
0 & 0 & 0 & 0
\end{pmatrix} + \begin{pmatrix}
0 & 0 & \frac{1}{2} a^2 & \frac{1}{2} a^3\\
0 & 0 & 0 & \frac{1}{2} a^2\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0
\end{pmatrix} + \begin{pmatrix}
0 & 0 & 0 & \frac{1}{6} a^3\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0
\end{pmatrix}$$

$$C = \begin{pmatrix}
0 & a & a^2 & \frac{5}{6} a^3\\
0 & 0 & a & a^2\\
0 & 0 & 0 & a\\
0 & 0 & 0 & 0
\end{pmatrix} + \begin{pmatrix}
0 & 0 & 0 & \frac{1}{6} a^3\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0
\end{pmatrix} = \begin{pmatrix}
0 & a & a^2 & a^3\\
0 & 0 & a & a^2\\
0 & 0 & 0 & a\\
0 & 0 & 0 & 0
\end{pmatrix} = A$$

De esta manera nos damos cuenta que $C = A$, por lo tanto, la anterior afirmación es cierta, la sumatoria de $B$ es igual a $A$