---
title: "Taller evaluable 1"
author: "Daniel Eduardo Macias Estrada"
subtitle: "AL y MD - 21/12/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Ejercicio 1

Halla el cociente y el resto de la división de $p(x) = (x+1)^7$ entre $q(x) = x^2+x+1$.

$$\frac{(x+1)^7}{x^2+x+1} = \frac{x^7+7x^6+21x^5+35x^4+35x^3+21x^2+7x+1}{x^2+x+1}$$

$$x^5 + \frac{6x^6+20x^5+35x^4+35x^3+21x^2+7x+1}{x^2+x+1} = x^5+6x^4+\frac{14x^5+29x^4+35x^3+21x^2+7x+1}{x^2+x+1}$$

$$= x^5 + 6x^4 + 14x^3 + \frac{15x^4+21x^3+21x^2+7x+1}{x^2+x+1} = x^5 + 6x^4 + 14x^3 + 15x^2 +\frac{6x^3+6x^2+7x}{x^2+x+1}$$

$$= x^5 + 6x^4 + 14x^3 + \frac{15x^4+21x^3+21x^2+7x+1}{x^2+x+1} = x^5 + 6x^4 + 14x^3 + 15x^2 +\frac{6x^3+6x^2+7x}{x^2+x+1}$$

$$= x^5 + 6x^4 + 14x^3 + 15x^2 + 6x + \frac{x+1}{x^2+x+1} $$

Comprobación en Python

```{python}
import numpy as np
p = np.poly1d([1,7,21,35,35,21,7,1])
q = np.poly1d([1,1,1])

r = p/q

r[0]
# Cociente

r[1]
#Resto
```


## Ejercicio 2
Halla el módulo y el árgumento del número complejo $\frac{(1+i)^7}{1-i}$.

$$z_1 = (1+i) = re^{i\varphi} \qquad r = |z_1| = \sqrt{1^2 + 1^2} = \sqrt{2} \qquad \varphi = \text{arg}(z_1) = \text{arctan} \bigg(\frac{b}{a} \bigg) = \text{arctan} \bigg(\frac{1}{1} \bigg) = \frac{1}{4}\pi$$

$$z_1 = \sqrt{2}e^{i \cdot \frac{1}{4}\pi} \qquad {z_1}^7 = (\sqrt{2}e^{i \cdot \frac{1}{4}\pi})^7 = 8\sqrt{2}e^{i (\frac{7}{4}\pi)} = 8\sqrt{2} \bigg( \text{cos}\bigg( \frac{7}{4}\pi \bigg) + i \cdot \text{sen} \bigg( \frac{7}{4}\pi \bigg) \bigg)$$

$${z_1}^7 = 8\sqrt{2} \bigg( \frac{\sqrt{2}}{2} - i \cdot \frac{\sqrt{2}}{2} \bigg) = 8(1-i)$$

$$r = \frac{{z_1}^7}{1-i} = \frac{8(1-i)}{1-i} = 8 $$

Esto implica que 

$$|r| = \sqrt{(8)^2 + (0)^2} = \sqrt{8^2} = 8 \qquad \text{arg}(r) = \text{arctan}\bigg( \frac{0}{8} \bigg) = 0$$

Comprobación en Python
```{python}
import cmath
z1 = complex(1,1)**7
z2 = complex(1,-1)
r = z1/z2
print(r)

abs(r)
#Modulo |r|

cmath.phase(r)
#Argumento arg(r)
```


## Ejercicio 3

Halla el valor de la matriz X para que se verifique

$$A \cdot X \cdot A^t = \sqrt{5} \cdot A$$

donde A es la matriz

$$A =  \begin{pmatrix}
1 & 1 & 1\\ 0 & -1 & -1\\ -1 & 0 & 1
\end{pmatrix}$$

$$A^{-1} \cdot A \cdot X \cdot A^t = A^{-1} \cdot \sqrt{5} \cdot A \quad \implies \quad X \cdot A^t = \sqrt{5}$$
$$X \cdot A^t \cdot {A^t}^{-1} = \sqrt{5} \cdot {A^t}^{-1} \quad \implies \quad X = \sqrt{5} \cdot {A^t}^{-1}$$

$$A^t = \begin{pmatrix}
1 & 0 & -1\\ 1 & -1 & 0\\ 1 & -1 & 1
\end{pmatrix} \qquad {A^t}^{-1} = \begin{pmatrix}
1 & -1 & 1\\ 1 & -2 & 1\\ 0 & -1 & 1
\end{pmatrix}$$

$$X = \sqrt{5} \cdot {A^t}^{-1} = \sqrt{5} \begin{pmatrix}
1 & -1 & 1\\ 1 & -2 & 1\\ 0 & -1 & 1
\end{pmatrix} = \begin{pmatrix}
\sqrt{5} & -\sqrt{5} & \sqrt{5}\\ \sqrt{5} & -2\sqrt{5} & \sqrt{5}\\ 0 & -\sqrt{5} & \sqrt{5}
\end{pmatrix}$$

## Ejercicio 4 

Resuelve aplicando el método de Gauss y clasifica según corresponda el sistema de ecuaciones lineal siguiente

$$\left\{\begin{matrix}
x & - & y & + & z & + & t & = & 4\\
2x & + & y & - & 3z & + & t & = & 4\\
x & - & 2y & + & 2z & - & t & = & 3\\
x & - & 3y & + & 3z & - & 3t & = & 2
\end{matrix} \right .$$

La representación matricial del sistema es el siguiente

$$A = \begin{pmatrix}
1 & -1 & 1 & 1\\
2 & 1 & -3 & 1\\
1 & -2 & 2 & -1\\
1 & -3 & 3 & -3
\end{pmatrix} \qquad X = \begin{pmatrix} x\\y\\z\\t \end{pmatrix} \qquad b = \begin{pmatrix} 4\\4\\3\\2 \end{pmatrix}$$

Mediante el teorema de Rouché-Frobenius se determinará el tipo de sistema que es

$$A \sim f_2-2f_1 \begin{pmatrix}
1 & -1 & 1 & 1\\
0 & 3 & -5 & -1\\
1 & -2 & 2 & -1\\
1 & -3 & 3 & -3
\end{pmatrix} \sim f_3-f_1 \begin{pmatrix}
1 & -1 & 1 & 1\\
0 & 3 & -5 & -1\\
0 & -1 & 1 & -2\\
1 & -3 & 3 & -3
\end{pmatrix} \sim f_4-f_1 \begin{pmatrix}
1 & -1 & 1 & 1\\
0 & 3 & -5 & -1\\
0 & -1 & 1 & -2\\
0 & -2 & 2 & -4
\end{pmatrix}$$

$$\sim \bigg( \frac{1}{3} \bigg)f_2 \begin{pmatrix}
1 & -1 & 1 & 1\\
0 & 1 & -^5/_3 & -^1/_3\\
0 & -1 & 1 & -2\\
0 & -2 & 2 & -4
\end{pmatrix} \sim f_3+f_2 \begin{pmatrix}
1 & -1 & 1 & 1\\
0 & 1 & -^5/_3 & -^1/_3\\
0 & 0 & -^2/_3 & -^7/_3\\
0 & -2 & 2 & -4
\end{pmatrix} \sim f_4+2f_2 \begin{pmatrix}
1 & -1 & 1 & 1\\
0 & 1 & -^5/_3 & -^1/_3\\
0 & 0 & -^2/_3 & -^7/_3\\
0 & 0 & -^4/_3 & -^{14}/_3
\end{pmatrix}$$

$$\sim \bigg( -\frac{3}{2} \bigg)f_3 \begin{pmatrix}
1 & -1 & 1 & 1\\
0 & 1 & -^5/_3 & -^1/_3\\
0 & 0 & 1 & ^7/_2\\
0 & 0 & -^4/_3 & -^{14}/_3
\end{pmatrix} \sim f_4+ \bigg( \frac{4}{3} \bigg) f_3 \begin{pmatrix}
1 & -1 & 1 & 1\\
0 & 1 & -^5/_3 & -^1/_3\\
0 & 0 & 1 & ^7/_2\\
0 & 0 & 0 & 0
\end{pmatrix}$$

Esto quiere decir que $rg(A) = 3$

$$(A|B) \sim f_2-2f_1 \begin{pmatrix}
1 & -1 & 1 & 1 & | & 4\\
0 & 3 & -5 & -1 & | & -4\\
1 & -2 & 2 & -1 & | & 3\\
1 & -3 & 3 & -3 & | & 2
\end{pmatrix} \sim f_3-f_1 \begin{pmatrix}
1 & -1 & 1 & 1 & | & 4\\
0 & 3 & -5 & -1 & | & -4\\
0 & -1 & 1 & -2 & | & -1\\
1 & -3 & 3 & -3 & | & 2
\end{pmatrix}$$

$$\sim f_4-f_1 \begin{pmatrix}
1 & -1 & 1 & 1 & | & 4\\
0 & 3 & -5 & -1 & | & -4\\
0 & -1 & 1 & -2 & | & -1\\
0 & -2 & 2 & -4 & | & -2
\end{pmatrix} \sim \bigg( \frac{1}{3} \bigg)f_2 \begin{pmatrix}
1 & -1 & 1 & 1 & | & 4\\
0 & 1 & -^5/_3 & -^1/_3 & | & -^4/_3\\
0 & -1 & 1 & -2 & | & -1\\
0 & -2 & 2 & -4 & | & -2
\end{pmatrix}$$

$$\sim f_3+f_2 \begin{pmatrix}
1 & -1 & 1 & 1 & | & 4\\
0 & 1 & -^5/_3 & -^1/_3 & | & -^4/_3\\
0 & 0 & -^2/_3 & -^7/_3 & | & -^7/_3\\
0 & -2 & 2 & -4 & | & -2
\end{pmatrix} \sim f_4+2f_2 \begin{pmatrix}
1 & -1 & 1 & 1 & | & 4\\
0 & 1 & -^5/_3 & -^1/_3 & | & -^4/_3\\
0 & 0 & -^2/_3 & -^7/_3 & | & -^7/_3\\
0 & 0 & -^4/_3 & -^{14}/_3 & | & -^{14}/_3
\end{pmatrix}$$

$$\sim \bigg( -\frac{3}{2} \bigg)f_3 \begin{pmatrix}
1 & -1 & 1 & 1 & | & 4\\
0 & 1 & -^5/_3 & -^1/_3 & | & -^4/_3\\
0 & 0 & 1 & ^7/_2 & | & ^7/_2\\
0 & 0 & -^4/_3 & -^{14}/_3 & | & -^{11}/_3
\end{pmatrix} \sim f_4+ \bigg( \frac{4}{3} \bigg) f_3 \begin{pmatrix}
1 & -1 & 1 & 1 & | & 4\\
0 & 1 & -^5/_3 & -^1/_3 & | & -^4/_3\\
0 & 0 & 1 & ^7/_2 & | & ^7/_2\\
0 & 0 & 0 & 0 & | & 0
\end{pmatrix}$$

De esta manera comprobamos que $rg(A|B) = 3$

Como $\text{rg}(A) = \text{rg}(A|B)$, según el teorema de Rouché-Frobenius, podemos afirmar que el sistema es compatible. Sin embargo el rango es menor que el orden, $rg(A) < n$, por lo tanto el sistema es compatible indeterminado

Las operaciones para determinar la matriz $X$ son las siguientes

$$t \in \mathbb{R} \qquad z + \frac{7}{2}t = \frac{7}{2} \implies z = \frac{7}{2}-\frac{7}{2}t$$

$$y - \frac{5}{3}z - \frac{1}{3}t = -\frac{4}{3} \implies y - \frac{5}{3} \bigg( \frac{7}{2}-\frac{7}{2}t \bigg) - \frac{1}{3}t = -\frac{4}{3} \implies y - \frac{35}{6} + \frac{35}{6}t - \frac{1}{3}t = -\frac{4}{3}$$

$$y + \frac{11}{2}t = -\frac{4}{3} + \frac{35}{6} \implies y + \frac{11}{2}t = \frac{9}{2} \implies y = \frac{9}{2} - \frac{11}{2}t$$

$$x - y + z + t = 4 \implies x - \bigg( \frac{9}{2} - \frac{11}{2}t \bigg) + \bigg( \frac{7}{2}-\frac{7}{2}t \bigg) + t = 4$$

$$x - \frac{9}{2} + \frac{11}{2}t + \frac{7}{2} - \frac{7}{2}t + t = 4 \implies x - \frac{2}{2} + \frac{6}{2}t = 4 \implies x - 1 + 3t = 4 \implies x = 5 - 3t $$

Por lo tanto el resultado de la matriz de incógnitas es el siguiente

$$X = \begin{pmatrix} 
5 - 3t\\ 
\frac{9}{2} - \frac{11}{2}t\\
\frac{7}{2}-\frac{7}{2}t\\
t
\end{pmatrix}$$

```{python}
from sympy import * 
from sympy.solvers.solveset import linsolve
x,y,z,t = symbols('x,y,z,t')

A = np.array([[1,-1,1,1],[2,1,-3,1],[1,-2,2,-1],[1,-3,3,-3]])
b = np.array([4,4,3,2])
AB = np.array([[1,-1,1,1,4],[2,1,-3,1,4],[1,-2,2,-1,3],[1,-3,3,-3,2]])

np.linalg.matrix_rank(A) == np.linalg.matrix_rank(AB)
# Comprobar que el sistema es compatible

np.linalg.matrix_rank(A) == 4
# Comprobar que el sistema es indeterminado

linsolve(Matrix(([1,-1,1,1,4],[2,1,-3,1,4],[1,-2,2,-1,3],[1,-3,3,-3,2])), (x,y,z,t))
# Solución
```



## Ejercicio 5

Considera el sistema de ecuaciones lineal

$$\left \{ \begin{matrix}
ax & + & y & + & z & = & (a-1)(a+2)\\
x & + & ay & + & z & = & (a-1)^2(a+2)\\
x & + & y & + & az & = & (a-1)^3(a+2)
\end{matrix} \right .$$

1. Indicar para qué valores del parámetro $a\in\mathbb{R}$ el sistema es compatible determinado, indeterminado o bien incompatible.

2. Resolver el sistema cuando $a=1$.

3. Resolver el sistema cuando $a=-2$.

### 1)
La representación matricial del sistema es el siguiente

$$A = \begin{pmatrix}
a & 1 & 1\\ 1 & a & 1 \\ 1 & 1 & a
\end{pmatrix} \qquad X =  \begin{pmatrix} x\\y\\z \end{pmatrix} \qquad b = \begin{pmatrix} 
(a-1)(a+2)\\ (a-1)^2(a+2)\\ (a-1)^3(a+2)
\end{pmatrix}$$

El determinante de la matriz tanto para la matriz $A$ como para su ampliada $|(A|B)|$ es el siguiente
$$|A| = a(a^2 - 1) - 1(a -1) + 1(1 - a) = a^3 - a - a + 1 + 1 - a = a^3 - 3a + 2$$

Para poder determinar el valor del rango debemos de tener claro que casos son los que dan valor 0 a la determinante.

$$|A| = a^3 - 3a + 2 = 0 \quad  \implies \quad (a-1)^2(a+2) = 0 \quad \implies \quad a = 1, a = -2$$

El sistema es compatible determinado cuando toma valores distintos a anteriormente obtenidos. 

$$\text{rg}(A) = \text{rg}(A|B) = 3 \quad \text{Si} \quad a \neq 1 \text{ y } a\neq -2$$

En el caso de que $a = 1$, tenemos que el determinante de $|A|$ es 0, al igual que el menor de orden 2. Sin embargo, cuando el menor es de orden 1, el determinante es 1

$$\begin{vmatrix}
1 & 1 & 1\\ 1 & 1 & 1\\ 1 & 1 & 1
\end{vmatrix} = (1)^3 - 3(1) +2 = 0 \qquad \begin{vmatrix}
1 & 1\\ 1 & 1
\end{vmatrix} = 0 \qquad |1| = 1$$

Debido a esto, $\text{rg}(A) = 1$. 

Por otro lado, el rango de la ampliada se define de la siguiente manera. Los determinantes de los menores de orden 3 son iguales a 0, al igual que los determinantes de los menores de orden 2. Solo con el determinante de orden 1 es posible obtener un valor distinto a 0 

$$\begin{vmatrix}
1 & 1 & 1\\ 1 & 1 & 1\\ 1 & 1 & 1 
\end{vmatrix} = 0 \qquad \begin{vmatrix}
1 & 1 & 0\\ 1 & 1 & 0\\ 1 & 1 & 0 
\end{vmatrix} = 0 \qquad \begin{vmatrix}
1 & 1\\ 1 & 1 
\end{vmatrix} = 0 \qquad \begin{vmatrix}
1 & 0\\ 1 & 0 
\end{vmatrix} = 0 \qquad |1| = 1$$

Debido a esto podemos decir que el rango de la ampliada es $\text{rg}(A|B) = 1$

Como ambas matrices tienen el mismo rango, el cual también es menor que el orden de la matriz $A$, concluimos que el sistema es compatible indeterminado 

$$\text{rg}(A) = \text{rg}(A|B) = 1 \quad \text{Si} \quad a = 1$$

Comprobación mediante python
```{python}
A = np.array([[1,1,1],[1,1,1],[1,1,1]])
AB = np.array([[1,1,1,0],[1,1,1,0],[1,1,1,0]])
np.linalg.matrix_rank(A) == np.linalg.matrix_rank(AB)
np.linalg.matrix_rank(AB)
```


En el caso de $a = -2$, se obtendra el rango de ambas matrices. Entendemos que el rango esta dado por el proceso de verificar si las determinantes de los menores dan 0 o no. El determinante de la matriz |A| esta dado por

$$\begin{vmatrix}
-2 & 1 & 1\\ 1 & -2 & 1\\ 1 & 1 & -2
\end{vmatrix} = (-2)^3 - 3(-2) + 2 = 0 \qquad \begin{vmatrix}
-2 & 1\\ 1 & -2
\end{vmatrix} = 3 \neq 0$$

Un menor de orden 2 no es igual a 0, lo que nos indica que $\text{rg}(A) = 2$

El rango de la ampliada es igual al de la matriz de coeficientes. Como el valor del rango es menor al valor del orden de $A$, entonces podemos afirmar que este es un sistema compatible indeterminado

Comprobación mediante python
```{python}
A = np.array([[-2,1,1],[1,-2,1],[1,1,-2]])
AB = np.array([[-2,1,1,0],[1,-2,1,0],[1,1,-2,0]])
np.linalg.matrix_rank(A) == np.linalg.matrix_rank(AB)
np.linalg.matrix_rank(AB)
```


### 2)
Resolver el sistema cuando $a=1$.

Teniendo en cuenta que la incógnita principal es $x$ pues el menor $|1|$ se forma por la primera columna. Además, debido a que no consideramos las dos últimas ecuaciones en el menor de orden 1, solo contemplamos la primer ecuación.

$$\left \{ \begin{matrix} x & + & y & + & z & = & 0 \end{matrix} \right .$$
$$\left \{ \begin{matrix} x & = & -z-y \end{matrix} \right .$$

Esto forma un sistema de Cramer de $A'X'=b'$

$$A'= \begin{pmatrix} 1 \end{pmatrix} \qquad X'=\begin{pmatrix} x \end{pmatrix} \qquad b'=\begin{pmatrix} -z-y \end{pmatrix}$$

Cuya solución es la siguiente

$$x = \frac{\begin{vmatrix} -z-y \end{vmatrix}}{1} = -z-y$$

$$X = \begin{pmatrix} -z-y\\ y\\ z \end{pmatrix}$$

Comprobación en Python
```{python}
linsolve(Matrix(([1,1,1,0], [1,1,1,0], [1,1,1,0])), (x,y,z))
```

### 2)
Resolver el sistema cuando $a=-2$.

Como las columnas que tomamos en el menor de orden 2 son las primeras dos, y aparte, se usa también las primeras dos ecuaciones, el sistema que se usa es el siguiente

$$\left \{ \begin{matrix} -2x & + & y & + & z & = & 0\\ x & + & -2y & + & z & = & 0 \end{matrix} \right .$$

$$\left \{ \begin{matrix} -2x & + & y & = & -z\\ x & + & -2y & = & -z \end{matrix} \right .$$

Como sistema de Cramer, queda de la siguiente forma

$$A' = \begin{pmatrix} -2 & 1\\ 1 & -2 \end{pmatrix} \qquad X' = \begin{pmatrix} x\\y \end{pmatrix} \qquad b' = \begin{pmatrix} -z\\ -z \end{pmatrix}$$

La solución, es la siguiente

$$x = \frac{\begin{vmatrix} -z & 1\\ -z & -2 \end{vmatrix}}{3} = \frac{3z}{3} = z$$

$$y = \frac{\begin{vmatrix} -2 & -z\\ 1 & -z \end{vmatrix}}{3} = \frac{3z}{3} = z$$

$$X = \begin{pmatrix} z\\ z\\ z \end{pmatrix}$$

Comprobación en Python
```{python}
linsolve(Matrix(([-2,1,1,0], [1,-2,1,0], [1,1,-2,0])), (x,y,z))
```
