---
title: "Tarea"
author: "Daniel Eduardo Macias Estrada"
date: "10/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)
library(polynom)
library(pracma)
```

## Tarea preliminares

#### Problema 2

```{r}
#1.-
a1 = 2+3i + 1+1i
a1

#2.-
a2 = 1+1i + 1-1i
a2

#3.-
aux = polynomial(coef=c(1,1,1))
aux2 = polynomial(coef=c(-1,1))
a3 = aux + aux2
a3
```


#### Problema 3

```{r}
k1 = 2+3i
k2 = 1+1i
k3 = 1-1i

#1.-
z1 = k1 * k2
z1

#2.-
z2 = k2 * k3
z2

#3.-
z3 = polynomial(coef=c(1,1,1)) * polynomial(coef=c(-1,1))
z3

#4.-
z4 = polynomial(coef=c(1,1))^2
z4

#5.-
z4 = polynomial(coef=c(1,1)) * polynomial(coef=c(-1,1))
z4
```

#### Problema 4

```{r}
# 1.-
q1 = 2+3i
Mod(q1)

# 2.-
q2 = 0+1i
Mod(q2)

# 3.-
q3 = 2+3i + 1+1i
Mod(q3)

# 4.-
q4 = 1+1i + 1-1i
Mod(q4)

# 5.-
q5 = k1 * k2
Mod(q5)

# 6.-
q6 = k2 * k3
Mod(q6)
```

#### Problema 5

```{python}
import numpy

x1 = numpy.poly1d([2,2])
x1.order

x2 = numpy.poly1d([1,0,0,0,3,2])
x2.order

x3 = numpy.poly1d([1,1,1]) * numpy.poly1d([1,-1])
x3.order

x4 = numpy.poly1d([1,1])**2
x4.order

x5 = numpy.poly1d([1,1]) * numpy.poly1d([1,-1])
x5.order
```

#### Problema 6

```{python}
t1 = numpy.poly1d([1,1]) # (x + 1)
t2 = numpy.poly1d([1,-1]) # (x - 1)
t3 = numpy.poly1d([1,0,1]) # (x^2 + 1)
t4 = numpy.poly1d([1,0,0,1]) # (x^3 + 1)
t5 = numpy.poly1d([1,-2,1]) # (x^2 - 2x + 1)
t6 = numpy.poly1d([1,2,1]) # (x^2 + 2x + 1)
t7 = numpy.poly1d([1,0,-1]) # (x^2 - 1)
t8 = numpy.poly1d([1,3,3,1]) # (x^3 + 3x^2 + 3x + 1)

t1**2 == t3

t1**2 == t6

t1**3 == t4

t1**3 == t8

t1*t2 == t7

t2**2 == t5

```

#### Problema 7

```{python}
y1 = numpy.poly1d([2,2])
y1.r

y2 = numpy.poly1d([1,0,0,0,3,2])
y2.r

y3 = numpy.poly1d([1,1,1]) * numpy.poly1d([1,-1])
y3.r

y4 = numpy.poly1d([1,1])**2
y4.r

y5 = numpy.poly1d([1,1]) * numpy.poly1d([1,-1])
y5.r
```

