---
title: "Vectores en Python"
author: "Daniel Eduardo Macias Estrada"
date: "30/1/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Vectores
Para crear un vector en Python, utilizamos **numpy.array()**

```{python vector}
import numpy as np
x = np.array([1,2,3,4,5,6,7,8,9,0])
x
```


### Longitud
Para calcular la longitud (la dimensión), utilizamos la función **len()**

```{python longitud}
len(x)
```


### Suma y resta de vectores
Sumar y restar dos o más vectores es muy simple, siempre y cuando sean de la misma dimensión

```{python sumres}
x = np.array([0,3,-1,3,5])
y = np.array([1,2,3,-1,0])
x+y
x-y
```


### Producto por un escalar
El producto por un escalar también funciona de forma sencilla

```{python prod}
x = np.array([1,0,-1,0,2,0,-2])
2*x
-2*x
5*x
```


### Producto escalar

```{python prodEscalar}
def productoEscalar(x,y):
    if(len(x) == len(y)):
        suma = 0
        for i in range(0,len(x)):
            suma = suma + x[i]*y[i]
        return suma
    else:
        return "Error: La dimensión de ambos vectores no son iguales"
 
        
x = np.array([0,3,-1,3,5])
y = np.array([1,2,3,-1,0])
productoEscalar(x,y)
```


### Norma euclídea
Para calcular la nomra de un vector, lo que hacemos es utilizar la función **numpy.linalg.norm()**

```{python norma}
x = np.array([1,2,0,3,-1,1])
np.linalg.norm(x)
import math
math.sqrt(productoEscalar(x,x))
```


### Distancia euclídea
Para calcular la distancia entre dos puntos, la definimos como la norma del vector que los une, es decir $\text{d}(x,y) = \Vert x-y \Vert$. En nuestro caso vamos a utilizar la función **distancia()**, la cual definimos del siguiente modo:

```{python distancia}
def distancia(x,y):
    if(len(x) == len(y)):
        return np.linalg.norm(x-y)
    else:
        return "Error: ambos puntos de pertenecen al mimo plano"
        
x = np.array([0,3,-1,3,5])
y = np.array([1,2,3,-1,0])
distancia(x,y)
```


### Ángulo entre dos vectores

```{python angulo}
def angulo(x,y):
    if(len(x) == len(y)):
        angulo = math.acos(productoEscalar(x,y) / np.linalg.norm(x)*np.linalg.norm(y))
        return angulo
    else:
        return "Error: los vectores no son de la misma dimensión"

x = np.array([0,3,-1,3,5])
y = np.array([1,2,3,-1,0])
angulo(x,y) * 180 / math.pi
```


### Proyección ortogonal

```{python proyeccion}
# Proyección y sobre x
def proyeccion(x,y):
    if(len(x) == len(y)):
        lam = productoEscalar(x,y) / productoEscalar(x,x)
        return lam * x
    else:
        return "Error: Los vectores no son de la misma dimensión"
        
x = np.array([3,1])
y = np.array([1,2])
proyeccion(x,y)
```


### Producto vectorial

```{python prodVectorial}
def productoVectorial(x,y):
    if(len(x) == len(y) and len(x)==3):
        return np.array([x[1]*y[2] - x[2]*y[1], x[2]*y[0] - x[0]*y[2], x[0]*y[1] - x[1]*y[0]])
    else:
        return "Error: No se cumples las condiciones para que se obtenga el producto vectorial"
        
x = np.array([1,2,3])
y = np.array([0,-1,1])
productoVectorial(x,y)
```


### Producto mixto

```{python prodMixto}
def productoMixto(x,y,z):
    if(len(x) == len(y) and len(x) == len(z) and len(x) == 3):
        return int(np.linalg.det(np.array([x,y,z])))
    else:
        return "Error"
        
x = np.array([1,2,3])
y = np.array([0,-1,1])
z = np.array([2,0,-3])
productoMixto(x,y,z)
```

